### ISSUE TITLE
SDCC Asm support?

### ISSUE THREAD

**Issue by tursilion** [santiontanon/mdlz80optimizer#10]
Any interest in adding support for the output of the SDCC compiler? Would love to see what it could do.

Sample output attached.

[ColCPlayerCommon.asm.txt](https://github.com/santiontanon/mdlz80optimizer/files/5025103/ColCPlayerCommon.asm.txt)

**Comment by santiontanon** [comment]
100% interested!! I've been wanting to add support for SDCC output for a while. I'll keep this ticket open so I remember to prioritize it ;)

Also, thanks a lot for the sample output!! It'll be very useful!

**Comment by santiontanon** [comment]
Initial support was added in version 0.9. But probably not very useful at this point, as I don't think MDL is easy to integrate with an SDCC compilation makefile. I'll be working on this for the next version :)

**Comment by santiontanon** [comment]
The latest version has fairly robust SDCC integration support, and I was able to integrate MDL into the makefile of Anchors Aweigh ( https://github.com/MartinezTorres/anchors_aweigh ), having MDL optimize each sdcc generated assembler file before assembling and linking. If there is interest, I will write a small tutorial on how to do it. But for now I'll close this issue as sdcc assembler syntax is supported :)

**Comment by tursilion** [comment]
That's pretty awesome, dude, thanks for following through on it!
