### ISSUE TITLE
Untracked hl usages

### ISSUE THREAD

**Issue by theNestruo** [santiontanon/mdlz80optimizer#16]
Usage of `hl` value in the `rld` and `rrd` instructions is not properly tracked, causing invalid _"Remove unused ld hl,nnnn (3 bytes, 11 t-states saved)"_ optimizations to be suggested.

**Comment by santiontanon** [comment]
oh, indeed! ok! that's an easy fix, I just missed adding HL to the input dependencies of those instructions in the z80*-instruction-set.tsv files! Will fix later after work. Thanks for reporting!!!

**Comment by santiontanon** [comment]
alright, resolved! I also added test42.asm to make sure this works! :)
