### ISSUE TITLE
Integration with vim

### ISSUE THREAD

**Issue by Fubukimaru** [santiontanon/mdlz80optimizer#21]
Hello!

I have checked MDL and I love it :). I would like to integrate it with vim, have you tried to do it?

If not I'll check how to do it and send you the information!

**Comment by Fubukimaru** [comment]
I couldn't stop myself and I started integrating it.

This can be done with vim without any plugins (at the moment only for INFO, I have to improve it).

In your vim configuration folder create a `compiler/mdlz80optimizer.vim` with the content:
```
if exists("b:current_compiler") | finish | endif
let b:current_compiler = "mdlz80optimizer"

if exists(":CompilerSet") != 2		" older Vim always used :setlocal
  command -nargs=* CompilerSet setlocal <args>
endif

let s:cpo_save = &cpo
set cpo&vim

CompilerSet makeprg=java\ -jar\ ~/bin/mdl.jar\ $*\ -dialect\ asmsx\ -po
CompilerSet errorformat=INFO:\ Pattern-based\ optimization\ in\ %f#%l:\ %m

let &cpo = s:cpo_save
unlet s:cpo_save
```
In the line makeprg set the command you'll use. In my case:
`CompilerSet makeprg=java\ -jar\ ~/bin/mdl.jar\ $*\ -dialect\ asmsx\ -po`
Which means, use the mdl.jar found in `/home/user/bin/`, pass the files and use dialect `asmsx` and option `-po`.

Then when editting you need to set MDL as the compiler with `:compiler mdlz80optimizer.vim` and then you'll be able to analyze the file with `:make file` and check the optimizations with `:copen`.

There are fancier ways to have this (with indications in the code and so on). I'll check how to do it :).

**Comment by santiontanon** [comment]
Very cool!!! I'll give it a try as soon as possible!! Thanks a lot for this! Once you are happy with it, do you mind if I add these instructions in the same way I added them for VSCode and Sublime?

**Comment by Fubukimaru** [comment]
Sure :). I'll have to investigate more.

Probably in the end I will give you two ways of configuring this:

- vim without plugins: More static and traditional analysis. You have to "make" it and then check the suggestions.
- vim with coc.vim: Check it on the go when saving.

I'll inform you when I get more results!

**Comment by santiontanon** [comment]
Great! Thanks a lot Fubukimaru!

**Comment by Fubukimaru** [comment]
New note: To add an icon or marker  next to the item to be optimized `cuteErrorMarker` plugin can be used (https://www.vim.org/scripts/script.php?script_id=2653)

I'll check how to add it to `coc.nvim` to get it with a popup.

**Comment by Fubukimaru** [comment]
I have dropped the idea of using `coc.vim` because it looks like it needs to have a language server always active and I think that's an overkill for this purpose.

Instead I have defined a command for F5:
`:nnoremap <F5> :compiler mdlz80optimizer \| :make % \| :cwindow <CR>`

It selects the optimizer and scans current file. If there is anything to optimize it will open a quickfix window (a split) to list the optimizations.

To use it we need to change the compiler configuration to this:
```
if exists("b:current_compiler") | finish | endif
let b:current_compiler = "mdlz80optimizer"

if exists(":CompilerSet") != 2		" older Vim always used :setlocal
  command -nargs=* CompilerSet setlocal <args>
endif

let s:cpo_save = &cpo
set cpo&vim

CompilerSet makeprg=java\ -jar\ ~/bin/mdl.jar\ -dialect\ asmsx\ -po\ $*
CompilerSet errorformat=INFO:\ Pattern-based\ optimization\ in\ %f#%l:\ %m

let &cpo = s:cpo_save
unlet s:cpo_save
```
And with this we can use the optimizer without any plugins if desired.

@santiontanon I think this should be sufficient to be able to work with it :)
![vim](https://user-images.githubusercontent.com/17855785/102143228-ee8f8680-3e63-11eb-942e-5c43d03a0f95.png)

**Comment by Fubukimaru** [comment]
Using vim-dispatch (https://github.com/tpope/vim-dispatch) the process can be run in the background
`:nnoremap <F6> :compiler mdlz80optimizer \| :Make %<CR>`

**Comment by Fubukimaru** [comment]
I haven't done any changes on this. I could write a guide as the way this approach works is good enough. What do you think @santiontanon ?

**Comment by santiontanon** [comment]
That would be great!!! No need to write much, just a few lines explaining how to do it, and I can test to see if I can reproduce on my end! You can past the text here, or do a pull request, up to you :)

**Comment by Fubukimaru** [comment]
Hello Santi!

Here's the pull request:
https://github.com/santiontanon/mdlz80optimizer/pull/25

If you need any help on reproducing it, just ping me :)

**Comment by santiontanon** [comment]
Awesome! heading to work in 3 minutes, but I'll check this out when I come back tonight! :)

**Comment by santiontanon** [comment]
Thanks for the pull request!! Awesome! Greatly appreciated! I'll close this ticket now :)
