### ISSUE TITLE
Optimize JP and JR

### ISSUE THREAD

**Issue by Fubukimaru** [santiontanon/mdlz80optimizer#23]
I had an issue in the asMSX assembler that may be useful for this project:
https://github.com/Fubukimaru/asMSX/issues/36

Do you think that optimizing the JP/JR makes sense for mdlz80?

**Comment by santiontanon** [comment]
Hi Fubukimaru, definitively! mdl should already do this, given the right flags. For example, if you would want mdl to let you know of all jp that can be turned into jr, you just have to add this flag to the command line: "-po size".

MDL's current optimizer is a pattern-based optimizer. It reads patterns from a file and applies them. By default (with "-po") it uses a file ( https://github.com/santiontanon/mdlz80optimizer/blob/master/src/main/resources/data/pbo-patterns.txt ) with patterns that optimize ensuring BOTH size and speed benefits. You can specify your own pattern file (-po "filename"), or use the "-po size" or "-po speed" flags to use alternative files that optimize focusing on size or focusing on speed. The "-po size" file includes patterns for jp->jr optimizations :)

**Comment by Fubukimaru** [comment]
Amazing job! Thanks Santi :)

I'm closing this then.
