### ISSUE TITLE
asMSX Macro system

### ISSUE THREAD

**Issue by Fubukimaru** [santiontanon/mdlz80optimizer#24]
Hello again!

And sorry for the issues :)

In the next release of asMSX we're going to include user macros (https://github.com/Fubukimaru/asMSX/issues/6). I have seen that mdlz80 recognizes them but fail with the number of parameters:

```
|| ERROR: Number of parameters in macro call incorrect!
|| ERROR: Problem instantiating macro cool_macro in code.asm#549: 	cool_marco	SOME_PARAM,60
```
With the following definition:
```
m_SOUND: MACRO #PAR1, #PAR2
	push	HL
	push	BC
	ld	C,#PAR1
	ld	HL,#PAR2
	call	FUNC
	pop	BC
	pop	HL
ENDM
```

I assume that it reads it using the syntax from other assembler, right?

We're currently implementing 2 ways of defining macros: compass-like and sjasm-like:

SJASM:
```
  macro BDOS #fun       ; macro definition
  ld c,#fun
  call 5
  endmacro
  BDOS 5               ; macro call
```

Compass:
```
BDOS: macro @fun
  ld c, @fun
  call 5
 endm
```

Both, definition and macro call, use comma to separate the parameters. Parameters must be preceded of # or @.

Would you be able to support this without much problem?

Thanks again!

**Comment by santiontanon** [comment]
Absolutely! This should be no problem at all! the base parser of MDL expects macro arguments to be just symbols, or to be preceded by a question mark "?", so, probably the "#" and "@" are being interpreted wrong in this case. But that's something super easy to add! Starting my work day in 5 minutes, but this is something I can add support for really quickly tonight. So, I'll ping this thread back once it's supported :)

**Comment by Fubukimaru** [comment]
Brillian! Thanks :)

**Comment by santiontanon** [comment]
done! I've created a new unit test with the 3 example macros you listed above (this file https://github.com/santiontanon/mdlz80optimizer/blob/master/src/test/resources/data/generationtests/asmsx-macros.asm should parse to this https://github.com/santiontanon/mdlz80optimizer/blob/master/src/test/resources/data/generationtests/asmsx-macros-expected.asm), and all seems to be working fine! 

1.2 release updated with this change as well! :)

**Comment by Fubukimaru** [comment]
Working perfectly. Thanks!
