### ISSUE TITLE
Character ! in labels in sjasmplus

### ISSUE THREAD

**Issue by abekermsx** [santiontanon/mdlz80optimizer#30]
Sjamplus supports using the character ! in labels, but it is not supported by mdlz80optimizer.

**Comment by santiontanon** [comment]
I just addressed this in the latest commit: https://github.com/santiontanon/mdlz80optimizer/commit/f87a18fa114e898b6d1c712e9ad689c55cd9db0e

It should be working in the upcoming release (or just compiling from source if you need it right away). I'll close this issue for now :)
