### ISSUE TITLE
Character ? at start of label in sjasmplus

### ISSUE THREAD

**Issue by abekermsx** [santiontanon/mdlz80optimizer#31]
Sjasmplus allows labels with the character ? in it, but not at the start of a label. Mdlz80optimizer doesn't show a warning if a labels starts with the character ?

**Comment by santiontanon** [comment]
What would be better behavior here you think? If dialect is "sjasmplus", should MDL just show a warning and continue? or would it be better to not allow labels with a "?" at the start in case of "sjasmplus"? A warning is a trivial 1-line fix with an if statement, but I wonder if some code base would count on the "?" not being part of the label, causing MDL to parse the line wrongly...

**Comment by abekermsx** [comment]
I guess it should be an error, but then again I doubt someone would accidently put a ? in front of a label when defining it.

If I put a ? before a label when using the label, sjasmplus display the following message:
warning: ?<symbol> operator is deprecated and will be removed in v2.x: ?label

I don't know if it will be allowed to start a label with ? in future versions of sjasmplus.

**Comment by ped7g** [comment]
the unary `?label` operator (undocumented and deprecated) can be used to enforce label-parsing of certain strings, ie.:
```
ix db 1,2,3,4
  ld a,(?ix+2)
```

As long as I'm co-maintaining and improving sjasmplus, the direction will go rather toward not allowing labels using reserved words like register names or instruction names, so `?label` operator shouldn't be needed as there shouldn't exist ambiguous source in the first place.

**Comment by santiontanon** [comment]
ok, sounds good! I also think letters and underscores is safer, specially since some assemblers use special characters like "?" or "@" to mark macro arguments, and allowing them at the beginning of labels can make the syntax ambiguous.

**Comment by santiontanon** [comment]
Ok, this is fixed with commit: https://github.com/santiontanon/mdlz80optimizer/commit/103242001b1b65afe0137b2de660e7e380cb1810

It should be included in the upcoming 2.3 release in a few days!
