### ISSUE TITLE
Sjasmplus directive FPOS is not supported

### ISSUE THREAD

**Issue by abekermsx** [santiontanon/mdlz80optimizer#33]
The Sjasmplus plus directive FPOS is not supported.

From it's documentation:
"The FPOS directive makes it possible to set the file position to anywhere in the output file. Position value without sign is used as absolute one to be set, position starting with + or - sign will be used as relative position."

Note that it only updates the position in the output file, not the Program Counter.

**Comment by santiontanon** [comment]
Support for this was added in commit https://github.com/santiontanon/mdlz80optimizer/commit/deb30f4d0d6d411ca018119d63abeddbe67e85e8

I added support for FPOS at the global level (i.e., MDL will recognize it regardless of the dialect), but if this causes issues, I can restrict it later on to only the sjasmplus dialect, as I think this is the only assembler that has this directive as far as I know (not sure if sjasm does too).

Anyway, this fix will be included in the upcoming 2.3 release! Thanks for reporting!
