### ISSUE TITLE
Include file syntax in sjasmplus

### ISSUE THREAD

**Issue by abekermsx** [santiontanon/mdlz80optimizer#35]
In Sjasmplus the characters < and > can be used around filenames, but it isn't supported by the mdlz80optimizer.

When using the < and > characters, the order in which directories sjasmplus looks for the file is changed. In this case it first checks the "root" directory, then the directories specified with --inc directive at the commandline and then the current directory.

This probably applies to all directives where filenames can be specified.

**Comment by santiontanon** [comment]
A fix for this is included in commit: https://github.com/santiontanon/mdlz80optimizer/commit/7f7fc86121f6004d1b08d81448f4e2f559e2db5c

I applied this to both include and incbin. Not sure if it should also be applied to other directives. But if it needs to be applied, feel free to reopen the issue, and I'll fix right away :)

This fix should be included in the upcoming 2.3 release
