### ISSUE TITLE
Allow multiple 'input assembler file'

### ISSUE THREAD

**Issue by abekermsx** [santiontanon/mdlz80optimizer#36]
At the moment only one file can be specified as input for the optimizer, but it would be nice if multiple files could be specified. I came across a codebase which uses this sjasmplus commandline feature.

**Comment by ped7g** [comment]
not sure about mdlz80, but in sjasmplus itself you can convert it to single-file-project by adding new wrapper asm file including all files in the same order as they are originally on the command line. I guess it may help to run it with mdlz80 too.

**Comment by abekermsx** [comment]
Yeah I know, it's easy to work around this issue, but still, I prefer to keep someone else's code/structure as-is before analysing it.

**Comment by santiontanon** [comment]
ah, this should be easy. What is the sjasmplus syntax for this? just specify all the files one after the other in the command line?

**Comment by ped7g** [comment]
yes, it reads them one by one as they appear on the command line, sort of concatenating them into one big file (although listing and error reporting does report particular file name and in case of default listing file I'm not even sure if one is created for each file or the first source does define the listing filename for all of them ... but that's not relevant to mdlz80 any way).

technically you can have in later versions even multiple console inputs, like `sjasmplus - x.asm -` -> will read console twice and between that parse x.asm as middle part.

**Comment by santiontanon** [comment]
Alright, support for multiple input files was added in commit: https://github.com/santiontanon/mdlz80optimizer/commit/dba992b483ebab421071448f93e7d273d7934ef6

All arguments that cannot be parsed as a flag are considered input files (before only the first was), and MDL now internally generates an auxiliar file that includes them all in case that more than one input file is specified. 

This fix should be included in the upcoming 2.3 release!

Thanks both for the explanations!
