### ISSUE TITLE
.incbin in SDCC/ASz80

### ISSUE THREAD

**Issue by artrag** [santiontanon/mdlz80optimizer#39]
For large projects in SDCC the ASM directive 

.incbin "nomafile.bin"

can be very handy to include data and should be supported by MDL

I use it C to include binary data in this way:
void sprite_patterns(void) __naked
{
__asm
    .incbin "knight_frm.bin"
__endasm;	
}
and then I cast to (char*) the name &sprite_patterns()

**Comment by santiontanon** [comment]
Oh, didn't realize this was not supported. Thanks for the report! It should be a one line change to map the ".incbin" in SDCC to the predefined "incbin" functinoality I think! I'll look into it this week, and update the current development build :)

**Comment by santiontanon** [comment]
alright, this should have been added in the latest dev release: https://github.com/santiontanon/mdlz80optimizer/releases/tag/v2.4dev

I'll close the issue, but let me know if I messed up adding this haha :)
