### ISSUE TITLE
PBO patterns

### ISSUE THREAD

**Issue by sverx** [santiontanon/mdlz80optimizer#43]
Are all the patterns for the PO all in this file
https://github.com/santiontanon/mdlz80optimizer/blob/master/src/main/resources/data/pbo-patterns.txt
?

Can I add patterns to the file directly or will need to recompile?

**Comment by sverx** [comment]
Well, actually I found that the pattern I was looking for is already in the list.

I have to admit that the pattern-based optimizer is pretty smart, honestly, but I guess after it performs one substitution it doesn't backtrack to the optimized code to try to optimize it further, at least I had this test block of code 'skip' one obvious optimization, I suspect because of the slightly less obvious one 'around' it.

I wrote this short case sample:

```
ld b,#2
ld a,#0
push af
ld c,#6
push bc
```
and I got:

```
    ld bc, 518
    ld a, #00
    push af
    push bc
```

instead of getting the expected:

```
    ld bc, 518
    xor a
    push af
    push bc

```

**Comment by santiontanon** [comment]
About the patterns: most patterns are in that file you point to. There are some additional ones in the "pbo-patterns-size.txt" and "pbo-patterns-speed.txt", but those two include the file you mention, and then just add a few extra.

As for "backtracking", the pattern-based optimizer currently only backtracks 2 instructions after applying an optimization (see line 292 here: https://github.com/santiontanon/mdlz80optimizer/blob/master/src/main/java/workers/pattopt/PatternBasedOptimizer.java ). But that might not be enough in this case. To cover these cases, I added the concept of "passes" (so the optimizer can do multiple passes through the codebase). You can trigger that with "-po1" (for 1 pass), "-po2" (for 2 passes) or "-po3" (for 3 passes).

As for your example, that's interesting! Indeed I would expect the "ld a,#0" to be replaced by "xor a" too! Let me take a look

**Comment by sverx** [comment]
> As for your example, that's interesting! Indeed I would expect the "ld a,#0" to be replaced by "xor a" too! Let me take a look

well, no, that was a mistake on my part as

```
ld a,#0
push af
```

and 

```
xor a
push af
```
won't result in the same outcome (as `xor a` would thrash flags)

**Comment by santiontanon** [comment]
Ah, I was typing fast, and didn't write what I wanted to write haha. I meant the "ld b,#2" and "ld c,#6" optimization. That one should happen now

**Comment by santiontanon** [comment]
I just tested and with the latest version in the repo I get this output:

`    ld bc, 1538
    xor a
    add a, c
    push af
    push bc
`

**Comment by sverx** [comment]
OK seems correct, good! :+1:

**Comment by santiontanon** [comment]
Great! I'll close the issue for now, but feel free to reopen if any issues arise :)
