### ISSUE TITLE
Stack new return optimization

### ISSUE THREAD

**Issue by ruyrybeyro** [santiontanon/mdlz80optimizer#46]
Hi,

This code:

POP HL ; drop return value in stack, shorter than ADD SP,2
LD HL,LEAVE ; we want to change return address to LEAVE
PUSH HL ; place LEAVE address in stack

can be replaced by:

LD HL,LEAVE ; we want to change return address to LEAVE
EX (SP),HL ; exchange top of stack and value in HL

Is it worth a new rule of optimization for MDL?

Regards

**Comment by santiontanon** [comment]
Oh, nice pattern! Yes, definitively! If HL is not used afterwards that saves 3 t-states and 1 byte (if I counted correctly :)).

**Comment by santiontanon** [comment]
Added in this commit! https://github.com/santiontanon/mdlz80optimizer/commit/50788c3e495a7fb013a6fef9c2401ef6addef80c

It will be incorporated in the next release (but, can also be used by just compiling from source form the latest version in GitHub, of course :) ).
