### ISSUE TITLE
Does not recognize DEFD while using dialect sjasmplus 

### ISSUE THREAD

**Issue by ruyrybeyro** [santiontanon/mdlz80optimizer#48]
Hi,

mdl does not recognise double words (4 bytes) sjasmplus syntax as in:

ROM_CRC defd 0                   
                   defd $b3667a2e, $c4614ab8, $5d681b02, $2a6f2b94, $b40bbe37, $c30c8ea1, $5a05df1b, $2d02ef8d

**Comment by santiontanon** [comment]
Ops! True! I forgot to add that keyword! Added (among some other details) in this commit: https://github.com/santiontanon/mdlz80optimizer/commit/e5f33da93e336371ee7cb422de125dd905eb604c
