### ISSUE TITLE
-so removes interrupt mode setup

### ISSUE THREAD

**Issue by taylorza** [santiontanon/mdlz80optimizer#50]
**Version: 2.5**

Loading the `I` register with a value and `IM  2` opcode is removed by the search-based operator.

Original code
```
ld hl,ivt ;Load IVT 
ld a,h    ; high byte
ld i,a    ; into I register
im 2      ;Switch to IM 2
```

Post search-based operator
```
ld hl,ivt ;Load IVT
```

**Comment by taylorza** [comment]
Looking at the commit history, I think this might already be fixed at least the loading of the `I` register.

**Comment by santiontanon** [comment]
Thanks! I just tested this, and the search-based optimizer does not remove anything here, but the pattern-based optimizer replaces the first two lines with "ld a, ivt >> 8", which is hl is not used afterwards should be correct :)

But yeah, there has been lots of commits that have not yet made it to the current release. Sorry about that! There is a big task that I want to complete before creating a new release, and I never seem to find time to complete it haha
