### ISSUE TITLE
Support for multiple instructions in one line (tniasm pipe)

### ISSUE THREAD

**Issue by theNestruo** [santiontanon/mdlz80optimizer#54]
When trying to run the optimizer on my code:
```
ERROR: expression failed to parse with token list: [|, nop, |, nop] in games/roadster/roadster.asm#324:                 nop     | nop   | nop
ERROR: parseRestofTheLine: Cannot parse line games/roadster/roadster.asm#324:           nop     | nop   | nop  left over tokens: [|, nop, |, nop]
ERROR: Error parsing source file games/roadster/roadster.asm in games/roadster/roadster.asm#324:                nop     | nop   | nop
ERROR: Problem parsing file games/roadster/roadster.asm
ERROR: Could not fully parse the code (error code 2).
5 errors.
```

The offending line (and other examples taken from the code):
```asm
	nop	| nop	| nop
```

```asm
	outi	| outi	| outi	| outi	| outi	| outi	| outi	| outi
```

```asm
; Player effects handler routines
	jp	DIRTY_RENDER_PLAYER_EFFECTS
	ret	| db	$ff, $ff ; (padding)
	ret	| db	$ff, $ff ; (padding)
	ret	| db	$ff, $ff ; (padding)
```

```asm
.PUSH_SPACE_KEY_DATA:
	dw	namtbl_buffer + 14 * SCR_WIDTH		| db	"PUSH SPACE KEY", $00
```

To be honest, tniasm is able to compile without the pipe separator ("|"), so the same code could please tniasm and mdlz80... but the synax highlight doesn't like it and I find the "zebra code effect" utterly unpleasant :D

Low priority to this issue, please. It's summertime and I am z80ing sparsely.

**Comment by santiontanon** [comment]
Oh, thanks! let me actually try to fix it right now, since I just fixed something else on tniasm.

**Comment by santiontanon** [comment]
Oh, but wait. How does tniasm resolve that? the last line is very tricky. How does tniasm know that "| db" is the beginning of a new statement, and not "or db" (where "db" is a symbol name)?

According to this tniasm manual (), tniasm interprets "|" only as instruction separator. But according to this example code that max_iwamoto shared a while ago ( https://www.msx.org/forum/msx-talk/development/assembler-optimizer?page=52 ), tniasm can interpret "|" as "or". I do not think it's possible to support both without having cases where there is ambiguity!

Maybe the solution is to add some flag to allow "|" as "or" in tniasm or not?

**Comment by theNestruo** [comment]
Thanks! I was taking a look at it but my laptop died before I could test the change on my assembly code:_D

**Comment by santiontanon** [comment]
Alright, I just added support for "|" in this commit: https://github.com/santiontanon/mdlz80optimizer/commit/7c1331f2e11711300a3838036aa06300be91f97a

To resolve the "|" as "or" issue I mentioned above, I added a new flag "-tniasm-pipe-as-or". If you don't pass it "|" is only used as statement separator in the tniasm dialect. If you pass it, it will also use it as "or", but if there is any ambiguity with statement separation, it's up to the programmer to resolve. I'll leave the issue open until you confirm it all works :)

**Comment by theNestruo** [comment]
About ambiguity: I'll do some tests tomorrow to know how tniasm solves it.
Wild guess: no symbol can have a mnemonic/directive as its name...

**Comment by santiontanon** [comment]
alright! great, let me know! If that's the case, I'll change that behavior, and remove the flag :)

**Comment by theNestruo** [comment]
Did a quick test and current solution is able to parse my code. Thank you very much!
Had to fix a platform-dependant test to build mdlz80 (already pull requested).

I'll do promised tests about ambiguity this afternoon (European time)

**Comment by ped7g** [comment]
I should probably bookmark this, so I have some simple example whenever somebody is asking me for even more relaxed syntax for that other assembler or asking me why I added options to make it more strict... :) Beautiful.

**Comment by santiontanon** [comment]
Ah, indeed. I think you are right about the 0.45 vs 1.0 versions! Let me see what can I do then, splitting tniasm 0.45 and 1.0 into separate dialects might be the cleanest thing. And thanks a lot for the additional "or" test cases, I'll double check MDL parses them the same way as tniasm tonight!

**Comment by santiontanon** [comment]
Ok! I think I resolved this with my last commit (I split the tniasm dialect into two, having in mind some of the differences that we have noticed). So, I'll resolve this for now (feel free to reopen if anything is still broken!)

**Comment by theNestruo** [comment]
Thanks a lot!
