### ISSUE TITLE
Wrong input registers in IN and OUT instructions

### ISSUE THREAD

**Issue by theNestruo** [santiontanon/mdlz80optimizer#56]
The input registers for the IN and OUT instructions are different in _z80msx-instruction-set.tsv_ ...

```tsv
IN A,(C)	14	ED 78	2	C		C		A	S,Z,N			true
IN A,(n)	12	DB n	2			n		A	S,Z,N			true
IN B,(C)	14	ED 40	2	C		C		B	S,Z,N			true
IN C,(C)	14	ED 48	2	C		C		C	S,Z,N			true
IN D,(C)	14	ED 50	2	C		C		D	S,Z,N			true
IN E,(C)	14	ED 58	2	C		C		E	S,Z,N			true
IN F,(C)	14	ED 70	2	C		C		F	S,Z,N			true
IN H,(C)	14	ED 60	2	C		C		H	S,Z,N			true
IN L,(C)	14	ED 68	2	C		C		L	S,Z,N			true
(...)
OUT (C),A	14	ED 79	2	A,C						C		true
OUT (C),B	14	ED 41	2	B,C						C		true
OUT (C),C	14	ED 49	2	C						C		true
OUT (C),D	14	ED 51	2	C,D						C		true
OUT (C),E	14	ED 59	2	C,E						C		true
OUT (C),H	14	ED 61	2	C,H						C		true
OUT (C),L	14	ED 69	2	C,L						C		true
OUT (n),A	12	D3 n	2	A						n		true
```

...than in _z80-instruction-set.tsv_ (and other _*-instruction-set.tsv_):

```tsv
IN A,(C)	12	ED 78	2	BC		C		A	S,Z,N			true
IN A,(n)	11	DB n	2	A		n		A	S,Z,N			true
IN B,(C)	12	ED 40	2	BC		C		B	S,Z,N			true
IN C,(C)	12	ED 48	2	BC		C		C	S,Z,N			true
IN D,(C)	12	ED 50	2	BC		C		D	S,Z,N			true
IN E,(C)	12	ED 58	2	BC		C		E	S,Z,N			true
IN F,(C)	12	ED 70	2	BC		C		F	S,Z,N			true
IN H,(C)	12	ED 60	2	BC		C		H	S,Z,N			true
IN L,(C)	12	ED 68	2	BC		C		L	S,Z,N			true
(...)
OUT (C),A	12	ED 79	2	A,BC						C		TRUE
OUT (C),B	12	ED 41	2	BC						C		TRUE
OUT (C),C	12	ED 49	2	BC						C		TRUE
OUT (C),D	12	ED 51	2	BC,D						C		TRUE
OUT (C),E	12	ED 59	2	BC,E						C		TRUE
OUT (C),H	12	ED 61	2	BC,H						C		TRUE
OUT (C),L	12	ED 69	2	BC,L						C		TRUE
OUT (n),A	11	D3 n	2	A,B						n		TRUE
```

It looks like the right values are the ones from _z80msx-instruction-set.tsv_.

**Comment by ped7g** [comment]
Technically the *z80-instruction-set.tsv* is correct, because Z80's `IN A,(C)` is using `BC` value to set address bus value.
But IIRC on MSX machines the upper 8 bits of I/O address space are not important, so optimization can ignore value in B, while for example on ZX Spectrum the upper 8bits could be important too (depending on the HW peripheral addressed), thus whole BC value has to be considered.

(I'm just **guessing** this is the reason for the difference in those files, I'm not familiar enough with MSX or mdlz80optimizer to *know*)

**Comment by ped7g** [comment]
But ...
`OUT (n),A	11	D3 n	2	A,B						n		TRUE`
this makes no sense to me. `out (n),a` will put value in A to upper 8 bits of address bus, B is not used at all with this one.

**Comment by santiontanon** [comment]
Yes, exactly, I was hoping to capture the difference in the way the z80 in an MSX and the z80 in a Spectrum handle the in/out instructions. But apparently, I did not correctly specify the "OUT (n),A".  And, oh, interesting about the parity thing, I'll double check this and try to fix tonight! Thanks for rising this issue!

**Comment by santiontanon** [comment]
I was looking at this in the z80 documented doc: http://www.z80.info/zip/z80-documented.pdf

and I am now very confused (Section 8.11 in page 35). Do you understand what do they mean there?! Almost all flags seem to be affected by the "IN r,(C)" instructions (apparently, not "IN A,(n)"!!)

**Comment by santiontanon** [comment]
Ok, I think I got it. I just checked the implementation of the Z80 emulator I use in MDL ( https://github.com/codesqueak/Z80Processor/blob/master/src/main/java/com/codingrodent/microprocessor/Z80/Z80Core.java#L2820 ), and it's quite clear over there (and now I understand the z80 documented doc).

**Comment by santiontanon** [comment]
I just pushed a fix, I hope I got it right this time haha. I'll close this issue, but please reopen if I messed it up (likely ;) )

**Comment by ped7g** [comment]
`in a,(n)` has to be binary mostly-compatible with 8080, `in r,(bc)` was new Zilog extension designed in their own way in the ED prefix zone. The `in a,(n)` still differs slightly from 8080 because of the overall I/O difference (using 16bit I/O address bus), but flags were kept compatible.

**Comment by theNestruo** [comment]
Thank you for the explanations, @ped7g!
I didn't knew about BC being used in other platforms, so sorry about the original issue. I'm glad that at least it helped to detect and fix another problem ^_^
