### ISSUE TITLE
incbin always null in DotGenerator.java

### ISSUE THREAD

**Issue by theNestruo** [santiontanon/mdlz80optimizer#8]
I haven't actually tested it yet, but pulled the code and this warning arose:

> `sb.append(nodeNames.get(s.incbin));` [DotGenerator.java#102](https://github.com/santiontanon/mdlz80optimizer/blob/master/src/main/java/workers/DotGenerator.java#L102)
> Unlikely argument type File for get(Object) on a Map<String,String>

Seems legit; nodeNames is a `Map<String, String>` and s.incbin is a `File`, hence this line will always append `"null"`.

**Comment by santiontanon** [comment]
Ah good one! "incbin" used to be a String with the filename, but now it's a File object, and forgot to update the DotGenerator worker! Thanks!! Fixed :)
